language: php

php:
  - 5.3
  - 5.4

before_script:
  - pear channel-discover drewish.github.com/phpredis
  - pecl install drewishPhpRedis/PhpRedis
  - phpenv rehash
  - composer install --dev
  - mkdir Snc && ln -s ../ Snc/RedisBundle
